/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStoreModalComponent: typeof import('./components/AddStoreModalComponent.vue')['default']
    AdminHeaderComponent: typeof import('./components/admin/AdminHeaderComponent.vue')['default']
    AdminSideBarComponent: typeof import('./components/admin/AdminSideBarComponent.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CartDialog: typeof import('./components/cashier/CartDialog.vue')['default']
    CashierHeaderComponent: typeof import('./components/cashier/CashierHeaderComponent.vue')['default']
    CashierSideBarComponent: typeof import('./components/cashier/CashierSideBarComponent.vue')['default']
    ChartByActiveUsersPerWeek: typeof import('./components/admin/ChartByActiveUsersPerWeek.vue')['default']
    ChartByExpenses: typeof import('./components/ChartByExpenses.vue')['default']
    ChartByMostSale: typeof import('./components/ChartByMostSale.vue')['default']
    ChartByProfit: typeof import('./components/ChartByProfit.vue')['default']
    ChartByProfitMonth: typeof import('./components/ChartByProfitMonth.vue')['default']
    ChartByProfitPerPeriod: typeof import('./components/ChartByProfitPerPeriod.vue')['default']
    ChartByPurchasePerPeriod: typeof import('./components/ChartByPurchasePerPeriod.vue')['default']
    ChartBySaleMonth: typeof import('./components/ChartBySaleMonth.vue')['default']
    ChartBySalePerPeriod: typeof import('./components/ChartBySalePerPeriod.vue')['default']
    ChartBySalePerPeroid: typeof import('./components/ChartBySalePerPeroid.vue')['default']
    ChartBySales: typeof import('./components/ChartBySales.vue')['default']
    ChartByStoresPerWeek: typeof import('./components/admin/ChartByStoresPerWeek.vue')['default']
    ChartByTopCustomer: typeof import('./components/ChartByTopCustomer.vue')['default']
    ChartByUsersPerWeek: typeof import('./components/admin/ChartByUsersPerWeek.vue')['default']
    FooterComponent: typeof import('./components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginComponent: typeof import('./components/LoginComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarComponent: typeof import('./components/SideBarComponent.vue')['default']
    StockHeaderComponent: typeof import('./components/stockcontroller/StockHeaderComponent.vue')['default']
    StockSideBarComponent: typeof import('./components/stockcontroller/StockSideBarComponent.vue')['default']
  }
}
