/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStoreModalComponent: typeof import('./components/AddStoreModalComponent.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChartByExpenses: typeof import('./components/ChartByExpenses.vue')['default']
    ChartByMostSale: typeof import('./components/ChartByMostSale.vue')['default']
    ChartByTopCustomer: typeof import('./components/ChartByTopCustomer.vue')['default']
    FooterComponent: typeof import('./components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginComponent: typeof import('./components/LoginComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarComponent: typeof import('./components/SideBarComponent.vue')['default']
  }
}
