/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/add-product': RouteRecordInfo<'/add-product', '/add-product', Record<never, never>, Record<never, never>>,
    '/add-purchase': RouteRecordInfo<'/add-purchase', '/add-purchase', Record<never, never>, Record<never, never>>,
    '/add-sale': RouteRecordInfo<'/add-sale', '/add-sale', Record<never, never>, Record<never, never>>,
    '/add-supplier': RouteRecordInfo<'/add-supplier', '/add-supplier', Record<never, never>, Record<never, never>>,
    '/create-employee': RouteRecordInfo<'/create-employee', '/create-employee', Record<never, never>, Record<never, never>>,
    '/create-store': RouteRecordInfo<'/create-store', '/create-store', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/employee': RouteRecordInfo<'/employee', '/employee', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/product': RouteRecordInfo<'/product', '/product', Record<never, never>, Record<never, never>>,
    '/store': RouteRecordInfo<'/store', '/store', Record<never, never>, Record<never, never>>,
    '/stores': RouteRecordInfo<'/stores', '/stores', Record<never, never>, Record<never, never>>,
    '/supplier': RouteRecordInfo<'/supplier', '/supplier', Record<never, never>, Record<never, never>>,
  }
}
