/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/add-employee': RouteRecordInfo<'/add-employee', '/add-employee', Record<never, never>, Record<never, never>>,
    '/add-product': RouteRecordInfo<'/add-product', '/add-product', Record<never, never>, Record<never, never>>,
    '/add-purchase': RouteRecordInfo<'/add-purchase', '/add-purchase', Record<never, never>, Record<never, never>>,
    '/add-sale': RouteRecordInfo<'/add-sale', '/add-sale', Record<never, never>, Record<never, never>>,
    '/add-supplier': RouteRecordInfo<'/add-supplier', '/add-supplier', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/register-user': RouteRecordInfo<'/admin/register-user', '/admin/register-user', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/cashier/check-receipt': RouteRecordInfo<'/cashier/check-receipt', '/cashier/check-receipt', Record<never, never>, Record<never, never>>,
    '/cashier/customer': RouteRecordInfo<'/cashier/customer', '/cashier/customer', Record<never, never>, Record<never, never>>,
    '/cashier/product': RouteRecordInfo<'/cashier/product', '/cashier/product', Record<never, never>, Record<never, never>>,
    '/cashier/sale': RouteRecordInfo<'/cashier/sale', '/cashier/sale', Record<never, never>, Record<never, never>>,
    '/check-receipt': RouteRecordInfo<'/check-receipt', '/check-receipt', Record<never, never>, Record<never, never>>,
    '/create-store': RouteRecordInfo<'/create-store', '/create-store', Record<never, never>, Record<never, never>>,
    '/customer': RouteRecordInfo<'/customer', '/customer', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/employee': RouteRecordInfo<'/employee', '/employee', Record<never, never>, Record<never, never>>,
    '/GeneralSettings': RouteRecordInfo<'/GeneralSettings', '/GeneralSettings', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/product': RouteRecordInfo<'/product', '/product', Record<never, never>, Record<never, never>>,
    '/purchase': RouteRecordInfo<'/purchase', '/purchase', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/sale': RouteRecordInfo<'/sale', '/sale', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/statistics': RouteRecordInfo<'/statistics', '/statistics', Record<never, never>, Record<never, never>>,
    '/stock': RouteRecordInfo<'/stock', '/stock', Record<never, never>, Record<never, never>>,
    '/stockcontroller/purchase': RouteRecordInfo<'/stockcontroller/purchase', '/stockcontroller/purchase', Record<never, never>, Record<never, never>>,
    '/stockcontroller/stock': RouteRecordInfo<'/stockcontroller/stock', '/stockcontroller/stock', Record<never, never>, Record<never, never>>,
    '/stockcontroller/supplier': RouteRecordInfo<'/stockcontroller/supplier', '/stockcontroller/supplier', Record<never, never>, Record<never, never>>,
    '/store': RouteRecordInfo<'/store', '/store', Record<never, never>, Record<never, never>>,
    '/stores': RouteRecordInfo<'/stores', '/stores', Record<never, never>, Record<never, never>>,
    '/supplier': RouteRecordInfo<'/supplier', '/supplier', Record<never, never>, Record<never, never>>,
  }
}
